XLabs/portal-bridge-ui

src/utils/consts.ts

Injective has its own Ethereum bridge and for INJ we will always be keep those via our bridge as canonical and don't want users to be fragmenting it via Wormhole

fix: disable INJ token

---

config-overrides.js

This PR fixes an issue with running `npm start` after the chunking change where it just hangs.

Webpack 5 splitChunks breaks WebpackDevServer fix

---

src/components/TokenSelectors/SolanaTokenPicker.tsx
src/hooks/useMetaplexData.ts
src/utils/metaplex.ts

For NFT tokens on the Solana network could happen that URI on metadata does not point to the NFT, and instead, it points to a metadata file, so if we detect it is a metadata file, we just go for it.
Solscan offer a button to navigate to the URI metadata
[Solscan Example](https://solscan.io/token/DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263#metadata)

#73 - add logic to fetch metaplet uri metadata whenever it is necessary

---

src/components/Transfer/SourceAssetWarning.tsx
src/utils/consts.ts

Display a **warning message** when trying to move `MATIC` token from `ETH` chain
Fixes #83
Ex: 
Warning message displayed:

feat: add warning when bridging MATIC token from ETH chain

---

src/contexts/SolanaWalletContext.tsx
src/hooks/useMetaplexData.ts

Solana token selector does not display NFT due to a CORS error, that produces an undefined for the entire NFT metadata, to avoid the undefined, the inner request was wrapped into a try-catch block, forcing to return a valid object, even if we can not retrieve the metadata to preview the NFT
Before
After

Solana token selector does not display NFT due an CORS error

---

src/components/Transfer/AddToMetamask.tsx
src/hooks/useHandleTransfer.tsx

The button "Add to Metamask" you see after finishing a transaction, was adding the wrong token if the transaction was a threshold's tBTC transaction with ethereum as the target. Fixed.
Also, removed some console.logs that were not needed.

Fix 'add to Metamask' for tBTC on Ethereum

---

package.json
src/components/TransactionProgress.tsx

Fixes #138 
- Add a message for `finality` on the `Polygon` chain transfer
> Waiting for finality on Polygon which may take up between 30 minutes to 3 hours to complete.

feat: add finality message for polygon chain

---

package-lock.json
package.json
src/components/Recovery.tsx
src/components/Transfer/AddToMetamask.tsx
src/components/Transfer/SendConfirmationDialog.tsx
src/components/Transfer/TokenWarning.tsx
src/hooks/useAllowance.ts
src/hooks/useCheckIfWormholeWrapped.ts
src/hooks/useFetchTargetAsset.ts
src/hooks/useHandleRedeem.tsx
src/hooks/useHandleTransfer.tsx
src/store/selectors.ts
src/store/transferSlice.ts
src/utils/consts.ts

This PR implements a refactor on the Threshold tBTC flow.
Before, we were allowing multiple wrapped tBTCs token to get generated: wTBTC-Eth, wTBTC-Opt, wTBTC-Arb and wTBTC-Pol. Those tokens were not 100% interchangeable between all the chains. It was possible to end up with double wrapped tokens.
Now, the only wrapped asset that is going to circulate on portal bridge is the wTBTC-Eth. If the source chain it's a threshold-supported chain like Optimism, and from there you send canonical tBTC to, for example, Avalanche. Instead of receiving wTBTC-Opt you will receive wTBTC-Eth. And you can swap that wTBTC-Eth for canonical tBTCs on any supported chain (be Optimism or any other)
Basically, you can send your tBTC from any chain to any other chain and you should never see two assets nor have …

Refactor tBTC flow

---

.github/workflows/production.yml

this update the event trigger to watch pr closed and triggers the jobs only if the PR got merged

fix issue related to trigger job on squash merge

---

src/utils/sanctions.ts

There are many users reporting they cannot use their wallets on Portal Bridge because they get blocked.
We think maybe TRM it's being so strict that ends up blocking non-malicious users.
For now, we only gonna block only the most malicious categories from using Portal Bridge.

Block only certain categories from using bridge

---

package-lock.json
package.json
src/utils/consts.ts

Fixes RPC errors when transferring tokens to/from terra classic. Native terra classic tokens still can't be redeemed until the contract is upgraded to support it.

terra parity upgrade fixes

---

src/components/Recovery.tsx
src/utils/consts.ts

Given the current throughput of Algorand, users are unable to redeem transactions that were made more than approximately 55 minutes ago. This limitation arises from the use of the `pendingTransactionInformation` endpoint in the Algorand client, which only supports requests for transactions up to 1000 blocks in the past. To retrieve any transaction beyond this limit, we need to utilize the Algorand indexer.
To solve this problem, I made the necessary request via the indexer. However, the transaction encoding differs between the two endpoints, so I performed a transformation of the latter to make it compatible with the parameter required by `parseSequenceFromLogAlgorand`.

Use algorand indexer to retrieve past transactions

---

package.json
src/components/PandleWarning.tsx
src/components/Transfer/Source.tsx

limit pandle transfer to ethereum -> bsc and bsc -> ethereum

#225 - limit pandle transfer to ethereum/bsc bsc/ethereum

---

.github/workflows/preview.yml
.github/workflows/production.yml
.github/workflows/testnet.yml
package.json
src/contexts/AlgorandWalletContext.tsx
src/contexts/EthereumProviderContext.tsx
src/index.js
src/muiTheme.js

WalletConnect v1 has been shut down, and now all Dapps must migrate to v2.
Use the WalletConnectWallet from the aggregator sdk, instead of the legacy version. This wallet requires a project id to be configured, which will be injected through env vars.
I've also had to fiddle with the mui dialog z-index in order to keep it behind the wallet connect dialog; I couldn't find an option to modify the later's z-index, but I suppose we can also override it through an old, plain, css file.

Switch WalletConnect to v2

---

src/components/ChainWarningMessage.tsx
src/components/Recovery.tsx
src/contexts/EthereumProviderContext.tsx
src/hooks/useVaaVerifier.ts

add a warning for VAAs not compatible with the token bridge to be redeemed, like CCTP for instance

#252 - add warning for VAAs not compatible

---

src/components/Transfer/Source.tsx

The problem was that when the wallet was disconnected, neither the token selected nor the amount input was hidden.

#124 - Token information box should not be displayed when user disconnects the wallet

---

package-lock.json
src/utils/consts.ts

It's an RPC error so here we updated the links

281 Failed to load token metadata SUI

---

package-lock.json
package.json
src/components/Migration/EvmQuickMigrate.tsx
src/components/SolanaCreateAssociatedAddress.tsx
src/components/Transfer/TokenWarning.tsx
src/hooks/useHandleRedeem.tsx

The canonical message must be shown when:
- Ethereum is the target and the asset is tBTC, the canonical message should be displayed.
- Any combination of source - target with eth, polygon, arbitrum, optimism, base, and solana, with tBTC.
I deleted the isWormholeWrapped condition because It's not necessary.
Result:

175 Bug fix 'Cannonical token' message is not displayed on “Are you sure?” pop-up

---

docs/docs/tutorials/how-to-deep-link.md
public/_redirects
src/components/Migration/EvmQuickMigrate.tsx
src/components/Recovery.tsx
src/components/SolanaCreateAssociatedAddress.tsx
src/hooks/useDeepLinkRecoveryParams.ts
src/hooks/useHandleRedeem.tsx
src/utils/parseChain.ts

- add deep link recovery support for vaa, move deep link docs

add deep link recovery support for vaa, move deep link docs

---

src/components/Transfer/AddToMetamask.tsx

According to the docs, Metamask supports symbols up to 11 characters.

update metamask wallet_watchAsset

---

src/config/transferRules.ts

enable native assets to bridge them out from terra classic

enable transfering native tokens out from terra classic

---

src/assets/providers/tbtc/solana/WormholeGateway.v2.ts

previous behavior: Sending tBTC from Solana to Avalanche for instance was giving an contract simulation error
current behavior: Sending tBTC from Solana to Avalance (or any non canonical chain) process successfully

add fix to allow sending canonical tBTC to non canonical supported network

---

package-lock.json
package.json
src/utils/consts.ts

Issue: https://github.com/XLabs/portal-bridge-ui/issues/521

[Feature] Include Celo liquidity pools

---

src/hooks/useGetSourceParsedTokenAccounts.ts

Fixes #515 
Update the type definition for data coming back from Covalent API endpoints to allow for nulls, and then guard against null values when enumerating NFT data

Add null-guards for token balances

---

apps/connect/src/components/atoms/NavBar.tsx

Hamburguer menu with breakpoint sm
Result:
https://github.com/XLabs/portal-bridge-ui/assets/35125931/70fad96d-2153-425e-a0ec-a775d7f902d0

Feature: Hamburguer menu

---

src/hooks/useGetSourceParsedTokenAccounts.ts

Fixes #559 
Update the type definition for data coming back from Covalent API endpoints to allow for nulls, and then guard against null values when enumerating NFT data

External data from Covalent API could be null

---

src/config/transferRules.ts

- removed rule that prevents bridge back wrapped native assets to terra classic

#689 - remove rule that prevents to transfer wrapped native assets back to terra classic

---

apps/token-list/package.json
apps/token-list/src/common.py
apps/token-list/src/gen.py

#724 - update token list references

---

.github/workflows/build.yml
.github/workflows/preview.yml
.github/workflows/production.yml
.github/workflows/testnet.yml
apps/connect/public/data/banners.json

Remove unnecessary input in workflow and update banner

---

src/App.tsx

Issue: https://github.com/XLabs/portal-bridge-ui/issues/798
Before:
After:

Bugfix: Overlap appbar

---

apps/connect/src/App.tsx
apps/connect/src/components/atoms/Background.tsx
apps/connect/src/components/atoms/NavBar.tsx
apps/connect/src/configs/messages.tsx
apps/connect/src/vite-env.d.ts
apps/connect/vite.token-bridge.config.ts
apps/connect/vite.usdc-bridge.config.ts

Issues:
- [Add staking link to header](https://github.com/XLabs/portal-bridge-ui-issues/issues/98)
- [Remove rewards link from usdc subpage](https://github.com/XLabs/portal-bridge-ui-issues/issues/100)
- [Remove few items from Portal (versioning and new tag)](https://github.com/XLabs/portal-bridge-ui-issues/issues/99)
- [Remove USDC Banner from Main Portal Page](https://github.com/XLabs/portal-bridge-ui-issues/issues/88)

Multiple fixes in Navbar, remove versioning and new tag

---

apps/connect/package.json
apps/connect/src/App.tsx
apps/connect/src/configs/messages.tsx
apps/connect/src/hooks/useFormatAssetParam.ts
apps/connect/src/hooks/useQueryParams.ts

Examples:
`?sourceChain=bsc&targetChain=arbitrum&asset=WETHbsc`
`?sourceChain=bsc&targetChain=arbitrum&asset=0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d`

Include token and requiredNetwork in query params

---

apps/connect/src/components/atoms/NavBar.tsx

[[bug] [Testnet] Wormholescan link redirects user to Mainnet stats](https://github.com/XLabs/portal-bridge-ui/issues/551)
https://github.com/XLabs/portal-bridge-ui/assets/19752365/6d2eb0df-7af3-4def-8fcf-c3954d00eb97
https://github.com/XLabs/portal-bridge-ui/assets/19752365/72c28d0b-78b8-49c3-9b6c-56326cddfa0e

[bug] [Testnet] Wormholescan link redirects user to Mainnet stats

---

apps/connect/src/App.tsx
apps/connect/src/hooks/useQueryParams.ts

[[bugs] Portal bridge transfer route has empty content](https://github.com/XLabs/portal-bridge-ui-issues/issues/109)
* Fixed router to use a wildcard for connect after trying to match the privacy policy route
* Change on the `useQueryParams` to allow for qs after url hashes (/#/transfer?qs...)
[https://preview.portalbridge.com/d656da0029/#/transfer?sourceChain=bsc&targetChain=arbitrum](https://preview.portalbridge.com/d656da0029/#/transfer?sourceChain=bsc&targetChain=arbitrum)

[bugs] Portal bridge transfer route has empty content

---

apps/connect/src/providers/telemetry.ts

Including other possible files like name and code

Improve message errors for telemetry

---

apps/connect/src/env/token-bridge.mainnet.ts

we need to revert this fix, since the symbol needs to match with the tokenKey
This reverts commit 4718f17972952325d62991f3c60978a5c1e9deff.

Revert "Fix wstETH symbol (#928)"

---

apps/connect/src/App.tsx
apps/connect/src/hooks/useQueryParams.test.ts
apps/connect/src/hooks/useQueryParams.ts

[Update query parameter functionality to be able to specify target asset](https://github.com/XLabs/portal-bridge-ui-issues/issues/106)
Since it's not possible to specify the target asset independently from the source asset, only the `route` qs was added which should cover the use case

Updated QS to be able to specify route

---

src/components/Recovery.tsx
src/utils/consts.ts

[Update VAA Repair/Redeem to support newest protocols in advanced tool ](https://github.com/XLabs/portal-bridge-ui-issues/issues/86)
Changed the flow to redirect to the new recovery tools pre-populated with the correct chain and tx

Update VAA Repair/Redeem to support newest protocols in advanced tool 

---

apps/connect/src/App.tsx
apps/connect/src/providers/sanctions.test.ts
apps/connect/src/providers/sanctions.ts

[TRM on connect](https://github.com/XLabs/portal-bridge-ui-issues/issues/116)
https://preview.portalbridge.com/4b5505c2b4/
* Both from/to addresses are checked
* If anything about the api fails (status error, inconsistent response, etc), transactions are `NOT` blocked
* If any address is sanctioned, transaction is blocked

TRM on connect

---

apps/connect/src/App.tsx
apps/connect/src/components/atoms/Banner.tsx
apps/connect/src/components/atoms/TableOfContent.tsx

[[bug] Failed to load wallets after returning from Privacy Policy page]([bug] Failed to load wallets after returning from Privacy Policy page)
* Moved the banner below connect's modals
* Removed a leftover `console.log`
* Code styling on router

[bug] Failed to load wallets after returning from Privacy Policy page

---

apps/connect/src/App.tsx
apps/connect/src/components/atoms/Connect.tsx
apps/connect/src/hooks/useConnectConfig.ts
apps/connect/src/hooks/useMessages.test.tsx
apps/connect/src/utils/getSortedChains.test.ts
apps/connect/src/utils/getSortedChains.ts
apps/connect/src/utils/top-symbols-by-volume.json

[[feat] - sort token list and network list based on wormholescan volume](https://github.com/XLabs/portal-bridge-ui-issues/issues/3)

[feat] - sort network list based on wormholescan volume

---

src/components/TokenSelectors/AlgoTokenPicker.tsx
src/components/TokenSelectors/TokenPicker.tsx

[[support] Algo assets are not searchable/selectable on the bridge, user id -736691227193245717](https://github.com/XLabs/portal-bridge-ui/issues/1003)

[support] Algo assets are not searchable/selectable on the bridge, user id -736691227193245717

---

apps/connect/src/env/token-bridge.mainnet.ts

- Coingeko Id is begin use to fetch quotes, without it the token does not get listed at the token picker

add xborg coingeko id

---

apps/connect-v1/src/hooks/useConnectConfig.ts
apps/connect-v1/src/navs/navs.test.ts
apps/connect-v1/src/providers/telemetry.test.ts
apps/connect-v1/src/providers/telemetry.ts
apps/connect/package-lock.json
apps/connect/package.json
apps/connect/src/hooks/useConnectConfig.ts
apps/connect/src/hooks/useQueryParams.test.ts
apps/connect/src/hooks/useQueryParams.ts
apps/connect/src/providers/telemetry.test.ts
apps/connect/src/providers/telemetry.ts
apps/connect/src/theme/connect.ts
apps/docs/docs/tutorials/how-to-deep-link.md

add preferred route and target asset param

---

src/hooks/useHandleTransfer.tsx

if the rawLogs are not present add them since wormhole SDK (legacy) use them to get the sequence
https://github.com/user-attachments/assets/c093d5af-c407-4713-b483-984b7e5a27f0

add rawLogs to injective tx if they are not present
