- src/App.js
- src/utils/consts.ts
Updated wormholenetwork.com links to the correct wormhole.com links.
> Updated wormholenetwork.com links

- package-lock.json
- package.json
To fix redeem native solana nft
> bumped wormhole-sdk

- src/config.ts
- Enable transfers from Karura
> enable transfers from Karura

- src/components/TokenSelectors/TokenPicker.tsx
- src/utils/consts.ts
Fix #17 
Changes:
- Add `DISABLED_TOKEN_REASONS`
- Refactor the `ListItem` code to the `TokenListItem` Component.
- `TokenListItem` Component handles if the token is disabled and shows the reason if any.
> feat: add alert message on disabled tokens

- src/utils/consts.ts
- Remove OPTIMISM Chain from Beta List (CHAIN_ID_OPTIMISM)
> fix: Remove OP from BETA list

- src/contexts/TerraWalletContext.tsx
- src/utils/consts.ts
- src/utils/parseError.ts
see https://github.com/XLabs/portal-bridge-ui/issues/63
> Error sending asset from BSC to Terra Classic

- src/utils/parseError.ts
Error messages were not being really specific. It was hard to answer users feedback. Fixed.
---
**BEFORE**
**AFTER**
> Fix error messages

- src/components/ConnectWalletButton.tsx
This PR implements a sanction list: if the address selected on the source or target chain it's a sanctioned address, we don't let the user operate.
https://user-images.githubusercontent.com/41705567/232599922-9ce153b7-a94f-4f10-ae5a-5e8beaf8a3da.mov
> Add sanction wallet list

- src/App.js
- src/components/NewsBar/index.tsx
- Add News Bar
- Add USDC Bridge Link
- Change Bridge to Token Bridge text link
> feat: add usdc bridge link & banner

- public/_redirects
- src/components/Transfer/index.tsx
- src/hooks/useDeepLinkTransferParams.ts
- src/hooks/useDeppLinkTransferParams.ts
redirect from:
- www.portalbridge.com/solana/from/ethereum
- www.portalbridge.com/23/from/4
- www.portalbridge.com/arbitrum/from/bsc
to:
- www.portalbridge.com/#/transfer?sourceChain=ethereum&targetChain=solana
- www.portalbridge.com/#/transfer?sourceChain=4&targetChain=23
- www.portalbridge.com/#/transfer?sourceChain=bsc&targetChain=arbitrum
> deep link redirect

- package-lock.json
- package.json
Should address #123
New version also adds icon and url for BitKeep wallet
> Bump aggregator sdk evm package version

- .github/workflows/production.yml
- package-lock.json
- package.json
- public/package.json
- src/components/Footer.tsx
- Added production.yml with steps to build and push an artifact to the github npm registry
- Add minor change at `src/components/Footer.tsx` to display the version
- Add failure at deploy time, due that the deploy hook is not yet implemented
> Prepare for moving building to github actions

- package.json
- public/sui/index.html
bump wormhole-connection version to 0.0.4
> bump wormhole-connection version to 0.0.4

- package-lock.json
- package.json
fixes https://github.com/XLabs/portal-bridge-ui/issues/104
> bump wormhole-sdk

- .github/workflows/preview.yml
- .github/workflows/production.yml
- .github/workflows/testnet.yml
- package.json
- public/sui/index.html
- src/App.js
setup usdc-stable build to migrate from stable.portalbridge.com to www.portalbridge.com/usdc-stable
> setup usdc-bridge build and preview deploy

- package-lock.json
- package.json
Should solve the issue with failing to connect a wallet due to the default APIs being down
> Bump aggregator sdk algorand package version

- package-lock.json
- package.json
update @terra-money/terra.js library version
>  #211 - update @terra-money/terra.js library version

- src/utils/consts.ts
Update injective endpoint to point to general grpc instead of k8s cluster
> #212 - update injective endpoint to point to general grpc instead of k8s cluster

- .github/workflows/preview.yml
- .github/workflows/testnet.yml
- package-lock.json
- package.json
- bumping version to retrigger cctp build and deploy
> usdc-bridge deploy

- package.json
- public/sui/index.html
- src/App.js
> update usdc bridge links

- package-lock.json
- package.json
- src/components/ShowTx.tsx
- src/components/TokenSelectors/TokenPicker.tsx
- src/hooks/useTerraMetadata.ts
- src/hooks/useXplaMetadata.ts
see https://github.com/XLabs/portal-bridge-ui/issues/140
> #140 - bump @solana/wallet-adapter-react version to 0.15.32

- package-lock.json
- package.json
The new version should stop prompting for user approval two times.
> bump aggregator sdk solana package version

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/ISSUE_TEMPLATE/support.yml
> update issue templates

- src/components/Recovery.tsx
bugfix enable recovery button even if vaa is not valid
> bugfix enable recovery button even if vaa is not valid

- package-lock.json
- package.json
> bump version before prod release

- package-lock.json
- package.json
Changelog:
- add tBTC v2 on Base mainnet
- add tBTC v2 on Base goerli for testnet build
> bump version to release tBTC v2 on Base mainnet

- src/App.js
Update banner text to include Arbitrum
> #286 - update banner text

- package.json
- src/components/NumberTextField.tsx
- src/store/selectors.ts
fix the scroll issue, limit input to the minimum supported amount
> fix scroll issue, limit input to the minimum supported amount

- package.json
- src/store/selectors.ts
> revert enforce decimals

- package-lock.json
- package.json
- src/components/TokenSelectors/TokenPicker.tsx
- src/utils/consts.ts
Summary:
* Show no native tokens
* Fix style issues in token list
* Update prettier
> 255 - Fix non native token hidden

- package-lock.json
- package.json
Release includes:
- https://github.com/XLabs/portal-bridge-ui/pull/311
- https://github.com/XLabs/portal-bridge-ui/pull/312
> bump version to 0.1.65

- public/sui/index.css
- public/sui/index.html
- src/App.js
- src/components/Migration/EvmQuickMigrate.tsx
- src/components/SolanaCreateAssociatedAddress.tsx
- src/hooks/useHandleRedeem.tsx
* Update banner text
* Fix prettier problem
Before:
Result:
> 339 Feature: Update Portal Bridge CCTP banner on main page to include optimism

- src/hooks/useGetSourceParsedTokenAccounts.ts
> 170 Bugfix: Two MATIC options are displayed on “Select a token” pop-up

- package-lock.json
- package.json
Changelog
- https://github.com/XLabs/portal-bridge-ui/pull/349
- https://github.com/XLabs/portal-bridge-ui/pull/350
- https://github.com/XLabs/portal-bridge-ui/pull/351
- https://github.com/XLabs/portal-bridge-ui/pull/352
> bump version to 0.1.70

- package-lock.json
- package.json
- Include USDC Bridge deployment
> #337 - bump version to deploy last USDC Bridge

- docs/docs/faqs/_liquid-markets/avax-oasis.md
- docs/docs/faqs/_liquid-markets/bsc-celo.md
- docs/docs/faqs/_liquid-markets/bsc-karura.md
- docs/docs/faqs/_liquid-markets/bsc-oasis.md
- docs/docs/faqs/_liquid-markets/matic-celo.md
- docs/docs/faqs/_liquid-markets/matic-karura.md
- docs/docs/faqs/_liquid-markets/matic-oasis.md
- docs/docs/faqs/liquid-markets.mdx
Related PRs:
* https://github.com/XLabs/portal-bridge-ui/pull/420
* https://github.com/XLabs/portal-bridge-ui/pull/419
* https://github.com/XLabs/portal-bridge-ui/pull/418
* https://github.com/XLabs/portal-bridge-ui/pull/417
* https://github.com/XLabs/portal-bridge-ui/pull/416
* https://github.com/XLabs/portal-bridge-ui/pull/415
* https://github.com/XLabs/portal-bridge-ui/pull/414
> Feature: Udpate docs

- apps/connect/src/App.tsx
- apps/connect/src/components/atoms/Background.tsx
- apps/connect/src/components/atoms/Footer.tsx
- apps/connect/src/components/atoms/NavBar.tsx
> Bugfix: Footer behavior

- .github/workflows/build.yml
- apps/connect/package-lock.json
- apps/connect/package.json
Issue: https://github.com/XLabs/portal-bridge-ui/issues/558
> Feat: Portal Logo should take the user back to the new portal bridge page

- .github/workflows/preview.yml
- .github/workflows/testnet.yml
- package-lock.json
- package.json
- src/contexts/InjectiveWalletContext.tsx
- src/utils/consts.ts
Update injective network library and set Mainnet Sentry as rpc
> xlabs/portal-bridge-ui-issues#1 - update injective library version

- apps/connect/package.json
The release will include:
- https://github.com/XLabs/portal-bridge-ui/pull/577
- https://github.com/XLabs/portal-bridge-ui/pull/592
- https://github.com/XLabs/portal-bridge-ui/pull/572
> 0.2.3 - bump version to release

- package-lock.json
- package.json
- src/contexts/SolanaWalletContext.tsx
> enable Solana wallets

- apps/connect/package.json
- bump version to deploy advanced-tools -> https://github.com/XLabs/portal-bridge-ui/pull/618
> bump version to deploy advanced-tools

- src/App.tsx
- src/components/Attest/index.tsx
https://github.com/XLabs/portal-bridge-ui/assets/1277510/cc978d10-afa8-4f74-8187-ff69c822c10e
> add xAssets link

- package.json
- src/components/NFTOriginVerifier.tsx
- src/components/ShowTx.tsx
- src/components/SmartAddress.tsx
- src/utils/consts.ts
- src/utils/metaMaskChainParameters.ts
Changes avascan explorer for snowtrace explorer
> Avascan to Snowtrace

- apps/connect/package-lock.json
- apps/connect/package.json
To do the deploy and upload this change:
https://github.com/XLabs/portal-bridge-ui/pull/634
> Bump version

- .github/workflows/build.yml
- gzip command to compress main.js file
- reduce size from 20mb to 4.5mb
> #630 - add gzip main.js file

- .github/workflows/build.yml
- .github/workflows/preview.yml
- .github/workflows/production.yml
- apps/rewards-dashboard/src/constants.ts
-> setup WAC_URL for rewards dashboard
testnet: https://wac.staging.gfx.town
mainnet (prod/preview): https://wac.gfx.xyz/
> setup WAC_URL for rewards dashboard

- .github/workflows/build.yml
- .github/workflows/preview.yml
- .github/workflows/production.yml
- .github/workflows/testnet.yml
- apps/rewards-dashboard/src/providers/Web3Provider.tsx
add url param to web3modal 
previous behavior: try to connect using Wallet Connect results in a reject 
current behavior: using wallet connect, now connects without issue
https://github.com/XLabs/portal-bridge-ui/assets/1277510/615be721-ae5a-45d4-afe5-31239cc8cc83
> add url param to web3modal

- src/hooks/useHandleTransfer.tsx
- src/utils/consts.ts
Issue: https://github.com/XLabs/portal-bridge-ui/issues/643
Results:
https://wormholescan.io/#/tx/0xc17309f22cad4832ef51ff43989d63cf850f51e4ae86469a30efa92f6b2ccb46?network=TESTNET&view=rawdata
https://goerli.basescan.org/tx/0x994887fa407ef47a9c32723af98a4fbe632ee7595b27a1cf058ff83ea1034b91
https://wormholescan.io/#/tx/0x805d4430dc55e5143537faadc17886cc309ddbb0a4f4ee16b9e885d8933cc1de?network=TESTNET&view=rawdata
> Fix unable to send tbtc with Aptos as a source

- apps/connect/src/components/ConnectLoader.tsx
update custom loader to load vite build
> update custom loader to load vite build

- .github/workflows/build.yml
- .github/workflows/testnet.yml
- apps/connect/vite.config.ts
add prefix and extra assets from wormhole connect
> add prefix and extra assets from wormhole connect

- package-lock.json
- package.json
- src/hooks/useGetIsTransferCompleted.ts
bugs/update wormhole sdk to skip empty txs send to algorand
> update wormhole sdk to skip empty txs send to algorand

- apps/connect/vite.config.ts
add evmos private RPC
Before: keeps loading
After: shows the result
> #654 - add evmos private RPC

- src/components/NewsBar/NewsBarButton.tsx
- src/components/NewsBar/index.tsx
- src/components/NewsBar/messages.tsx
Issue: https://github.com/XLabs/portal-bridge-ui-issues/issues/38
> Create Banner announcing Eth bridge launch (advanced tools)

- apps/connect/src/configs/messages.tsx
Issue: https://github.com/XLabs/portal-bridge-ui-issues/issues/38
>  Create Banner announcing Eth bridge launch

- src/components/NewsBar/messages.tsx
> Banner eth style fixes (advanced tools)

- apps/connect/src/configs/messages.tsx
> Banner eth style fixes

- src/components/Transfer/TransferLimitedWarning.tsx
- src/utils/consts.ts
Issue: https://github.com/XLabs/portal-bridge-ui-issues/issues/41
> Update governor limit messaging in advanced tool

- apps/connect/vite.config.ts
- apps/docs/docs/faqs/liquid-markets.mdx
depends on: https://github.com/wormhole-foundation/wormhole-connect/pull/1348
https://github.com/XLabs/portal-bridge-ui/assets/1277510/874b7c26-1eba-41c4-a7ac-9a935016c883
> add explorer option

- apps/connect/vite.config.ts
> portal-bridge-ui-issues#25 - add private rpcs

- src/components/ShowTx.tsx
- src/components/SmartAddress.tsx
- src/utils/consts.ts
Update AlgoExplorer references to use Pera Explorer
> update algoexplorer references

- apps/rewards-dashboard/src/components/Background.tsx
- apps/rewards-dashboard/src/constants.ts
- apps/rewards-dashboard/src/hooks/useWalletInfo.tsx
- apps/rewards-dashboard/src/index.css
- apps/rewards-dashboard/src/layouts/DashboardLayout.tsx
- apps/rewards-dashboard/src/locales/en.po
- apps/rewards-dashboard/src/providers/Web3Provider.tsx
- apps/rewards-dashboard/src/providers/index.tsx
- apps/rewards-dashboard/src/quarks/Glow.tsx
- apps/rewards-dashboard/src/quarks/StatWindow.tsx
- apps/rewards-dashboard/src/quarks/WalletManager.tsx
1. adds a cell for the beefy finance vault
2. adds a tooltip explaining the minimum
> add window for cusdc vault

- apps/connect/package-lock.json
- apps/connect/package.json
bump version to deploy wormhole connect at production@0.2.3
> bump version to deploy wormhole connect at production@0.2.3

- apps/connect/package-lock.json
- apps/connect/package.json
deploy wormhole connect production@0.2.4
> deploy wormhole connect production@0.2.4

- apps/connect/vite.token-bridge.config.ts
> #742 - add BONK asset configuration

- apps/connect/src/components/atoms/NavBar.tsx
https://github.com/XLabs/portal-bridge-ui/assets/1277510/3b411f7c-0b06-4995-a491-fde25e96a23b
> #741 - fix logo link

- .github/workflows/preview.yml
- .github/workflows/testnet.yml
- apps/connect/src/components/ConnectLoader.tsx
- apps/connect/vite.config.ts
when the integrity check changes, the url from where te resource gets loaded change, and force the browser to load a fresh file
> add parameter to refresh assets when a new versio gets deployed

- .github/workflows/preview.yml
- .github/workflows/testnet.yml
- apps/connect/src/components/ConnectLoader.tsx
- remove query param to avoid asset reload unnecessarily
- partially reverts https://github.com/XLabs/portal-bridge-ui/commit/5b60745b9fe1b21246856d8a280c49c63d65ecce
> remove query param to avoid asset reload unnecessarily

- src/components/Recovery.tsx
- src/components/Transfer/Source.tsx
- src/components/Transfer/Target.tsx
- src/config/transferRules.ts
- src/utils/consts.ts
> enable only scroll

- src/utils/consts.ts
> enable blast at token registry

- apps/connect/vite.config.ts
- apps/connect/vite.token-bridge.config.ts
> disable blast

- apps/connect/vite.token-bridge.config.ts
> re enable solana, injective, klaytn disabled by mistake

- src/utils/consts.ts
Issue: https://github.com/XLabs/portal-bridge-ui-issues/issues/68
> Change Terra rpc and Terra Classic fcd urls

- apps/connect/package-lock.json
- apps/connect/package.json
Change in this version (advanced-tools):
- [Enable attest recovery](https://github.com/XLabs/portal-bridge-ui/commit/39557bf28042b9e36de339c491a215ece03f48a3)
> Update version to 0.2.15

- apps/connect/vite.usdc-bridge.config.ts
> Change title: "USDC Bridge" to "USDC Transfer"

- apps/connect/vite.token-bridge.config.ts
> xlabs/portal-bridge-ui-issues#92 - add wombat exchange token config

- src/App.tsx
- src/components/NewsBar/messages.tsx
- src/components/ShowTx.tsx
- [remove USDC banner from advanced tools](https://github.com/XLabs/portal-bridge-ui-issues/issues/102)
- [Add staking link to header of Advanced tool](https://github.com/XLabs/portal-bridge-ui/issues/898)
> Multiple fixes in Navbar, and remove banner (Advanced tools)

- apps/connect/vite.token-bridge.config.ts
> Include ETHFI

- src/App.tsx
> Include privacy policy link

- .github/workflows/checks.yml
- apps/connect/jest.config.ts
- apps/connect/jest.setup.tsx
- apps/connect/package-lock.json
- apps/connect/package.json
- apps/connect/src/App.tsx
- apps/connect/src/hooks/useBannerMessage.ts
- apps/connect/src/hooks/useFormatAssetParam.test.ts
- apps/connect/tsconfig.json
[Add portal-bridge unit testing setup](https://github.com/XLabs/portal-bridge-ui-issues/issues/112)
* Added testing dependencies and config
* Added ci check
* Added example test
> Add portal-bridge unit testing setup

- apps/connect/package-lock.json
- apps/connect/package.json
- apps/connect/src/App.tsx
- apps/connect/src/providers/telemetry.ts
- apps/connect/src/utils/constants.ts
- Remove the `.identify(...)` function, as I saw that it gives some errors if there is more than one account on the device, and as we do not handle sessions anyway I do not think it is necessary.
- Save the error message to have more info.
- Change mixpannel token id depend of the environment.
> [metrics] Telemetrycs in production

- apps/connect/.eslintrc.cjs
- apps/connect/jest.config.ts
- apps/connect/package.json
- apps/connect/src/App.tsx
- apps/connect/src/components/atoms/NewsBar.tsx
- apps/connect/src/hooks/useBannerMessage.ts
- apps/connect/src/hooks/useBannerMessageConfig.test.tsx
- apps/connect/src/hooks/useBannerMessageConfig.ts
- apps/connect/src/hooks/useMessages.test.tsx
- apps/connect/src/hooks/useMessages.ts
- apps/connect/src/hooks/useQueryParams.test.ts
- apps/connect/src/hooks/useQueryParams.ts
- apps/connect/src/providers/telemetry.test.ts
- apps/connect/src/providers/telemetry.ts
- apps/connect/tsconfig.json
* Add coverage report
* Add testing baseline testing for hooks, etc
* Some cleanup/refactor after affected code got tested
> Add basic testing coverage

- apps/connect/index.html
- apps/connect/package-lock.json
- apps/connect/package.json
- apps/connect/vite.token-bridge.config.ts
- apps/connect/vite.usdc-bridge.config.ts
[[feat] - Improve SEO rank for USDC Bridge (CCTP)](https://github.com/XLabs/portal-bridge-ui-issues/issues/70)
* Added a vite plugin and base changes to be able to control meta built into `index.html`
-------
I'm unsure on what would be the ideal SEO changes needed, but looking at google NOW it seems the desired outcome was already reached
> [feat] - Improve SEO rank for USDC Bridge (CCTP)

- apps/connect/src/env/token-bridge.mainnet.ts
- apps/connect/src/env/token-bridge.testnet.ts
[Update Connect Portal config for W token and WOM](https://github.com/XLabs/portal-bridge-ui-issues/issues/101)
* WOM
* W
These changes were **NOT** tested locally
> Update Connect Portal config for W token and WOM

- apps/connect/src/providers/telemetry.test.ts
- apps/connect/src/providers/telemetry.ts
[Add additional mixpanel properties to events](https://github.com/XLabs/portal-bridge-ui-issues/issues/117)
https://preview.portalbridge.com/f3583aa118
> Add additional mixpanel properties to events

- apps/docs/docs/faqs/_liquid-markets/sol-arb.md
[Update Liquid Markets doc to include WIF routes](https://github.com/XLabs/portal-bridge-ui/issues/933)
> Update Liquid Markets doc to include WIF routes

- apps/connect/src/env/token-bridge.ts
- apps/connect/src/env/usdc-bridge.ts
Remove privacy policy from header nav
https://xlabs-org.slack.com/archives/C05SAKQ2284/p1722012342953139
> Remove privacy policy from header nav

- apps/connect/package-lock.json
- apps/connect/package.json
- apps/connect/src/providers/telemetry.test.ts
- apps/connect/src/providers/telemetry.ts
[Add additional mixpanel properties to events](https://github.com/XLabs/portal-bridge-ui-issues/issues/117)
Added USD notional amount
> Add additional mixpanel properties to events 2

- apps/connect/package-lock.json
- apps/connect/package.json
Issue: https://github.com/XLabs/portal-bridge-ui/issues/1022
> Include xLayer in validate condition

- apps/connect/src/env/token-bridge.testnet.ts
> setup correctly testnet networks

- apps/connect/src/env/token-bridge.mainnet.ts
> #130 - add Renzo NTT configs

- apps/connect/src/env/token-bridge.mainnet.ts
> Fix xbg icon

- apps/connect/package-lock.json
- apps/connect/package.json
> Update connect 0.3.20

- apps/connect/src/env/token-bridge.mainnet.ts
> add RENZO quoter for solana

- package-lock.json
- package.json
- src/contexts/AlgorandWalletContext.tsx
Issue: https://github.com/XLabs/portal-bridge-ui-issues/issues/131
> Remove MyAlgo

- apps/connect/package-lock.json
- apps/connect/package.json
https://github.com/user-attachments/assets/8f75541c-b90e-428d-a7a1-15e82bf4e060
> update connect version

- apps/connect/src/env/token-bridge.mainnet.ts
> Include Base ETHFI NTT

- apps/connect/src/hooks/useConnectConfig.ts
https://xlabs-org.slack.com/archives/C05SAKQ2284/p1726819491260269
https://preview.portalbridge.com/5b39878cdb/#/transfer?sourceChain=solana&targetChain=bsc&asset=sol
> [bug] query params not working

- apps/connect/src/env/token-bridge.mainnet.ts
Added `tBTC` to wrapped tokens so it gets support when pre loading it through qs
> [bug] Asset qs tBTC

- apps/connect/src/env/token-bridge.mainnet.ts
- [add solana quoter for ntt](https://github.com/XLabs/portal-bridge-ui/commit/f2f8b9252d5cc6fb1be72ee57dda1642cc5fc412)
- [fix ntt manager address for Agora](https://github.com/XLabs/portal-bridge-ui/commit/e1f1ae2a9b6a6c6477a1f3fccd91de688a3f83f9)
> fix ntt configs

- apps/connect/package-lock.json
- apps/connect/package.json
includes changes from:
- https://github.com/wormhole-foundation/wormhole-connect/releases/tag/development%401.0.0-beta.8
> set connect version to beta.8

- apps/connect-v1/src/env/token-bridge.ts
> Fix build config chains in Cosmos v1

- apps/connect/index.html
- apps/connect/public/manifest.json
* Added manifest required data
* Added cors config to manifest
> Add portal/connect embed into Safe Wallet

- apps/connect/src/env/common.ts
Issue: https://xlabs-xyz.atlassian.net/browse/POR-32
> New Kaia RPC

- apps/connect/package-lock.json
- apps/connect/package.json
- apps/connect/src/env/token-bridge.mainnet.ts
issue: https://xlabs-xyz.atlassian.net/browse/POR-54
> Add NTT Layer 3

- apps/connect/src/env/token-bridge.mainnet.ts
Issue: https://xlabs-xyz.atlassian.net/browse/POR-22
> Add Audius token

- apps/connect-v1/src/env/token-bridge.mainnet.ts
- apps/connect/src/env/token-bridge.mainnet.ts
> Remove Yaku

- apps/connect/src/env/token-bridge.mainnet.ts
> Add pStake Token Bridge

- apps/connect/src/env/token-bridge.mainnet.ts
> Fix Audius icon

- apps/connect/src/env/token-bridge.mainnet.ts
Issue: https://xlabs-xyz.atlassian.net/browse/POR-116
> Remove USDS and Sky

- src/icons/celo.svg
> Update Celo logo

- apps/connect/src/env/token-bridge.mainnet.ts
> add joe token config

- apps/connect/src/env/token-bridge.mainnet.ts
Tests:
https://wormholescan.io/#/tx/5xn2GUGDwXVAt8qse4NRG26MMfeBURHXAxwRRX6wtZC3uyySKKC1NzfD83MEsNeoBxaq3zTU7CrhPvnagaSXPJm2?view=overview
https://wormholescan.io/#/tx/0x38e080751f66907f99a83589ec5bef1ddd22209107522b41d99affce15c360da
> Add USDS v2 NTT

- apps/connect-v1/src/env/tbtc-bridge.ts
- apps/connect-v1/src/env/token-bridge.ts
- apps/connect/src/env/token-bridge.ts
- apps/connect/src/env/usdc-bridge.ts
- apps/rewards-dashboard/src/components/Header.tsx
> SubMenu closed as a default

- src/hooks/useHandleAttest.tsx
- src/hooks/useHandleTransfer.tsx
- src/utils/injective.ts
https://github.com/user-attachments/assets/c4b76f0e-d212-4ba3-a96a-65afb754be11
> extend fix to attest flow

- apps/connect-v1/src/components/atoms/NavBar.tsx
- apps/connect/src/components/atoms/NavBar.tsx
> Fix Submenu font size

- apps/connect/src/env/token-bridge.mainnet.ts
Arbitrum -> Solana https://wormholescan.io/#/tx/0x49f25b0a1e534431ddb5dcfad4795ba86da8c88953b0238059d314f24e05ae2b
Polygon -> Solana https://wormholescan.io/#/tx/0x14187a73f5fafff30f52aa5906b5eaa1f6856f435006cf1189016a25080942b7
Optimism -> Solana  https://wormholescan.io/#/tx/0x0d983cf52f4f0f20d27ec3e5d3aef0b1cd97366653db1ee452c458bafe82c391
Solana -> Arbitrum
https://wormholescan.io/#/tx/43v4tompvb1XJnRY5AaRnYTia6tMUNNZGCc8u1zjKpCSVZjWaDogW6MukdTi3iWqUhqwTahGRyNbTLcSnqQdnC2K
Solana -> Optimism
https://wormholescan.io/#/tx/4u5MQULCULNi4hve6U6P8NjVR8dtCtTpNMUUp9hat321KSvzekm44GjY4anRYaUgNNQ77k8LkF7TinUvem7f3zAE
Solana -> Polygon
https://wormholescan.io/#/tx/3q6wZpVgi2MeuEgKLWVjUdij1oyMKypGMejMX8gmkD6abERw87vkteDoAYZK4RQvBRPVdg8qgnBDGsDJmJhaEb4u
> NTT Layer3 Arbitrum, Polygon and Optimism

- apps/connect/src/env/token-bridge.mainnet.ts
Jira cards:
https://xlabs-xyz.atlassian.net/browse/POR-150
https://xlabs-xyz.atlassian.net/browse/POR-149
TOWER
Ethereum -> Solana https://wormholescan.io/#/tx/0x6c4058809c540a66059082ebb6adfcfe70d3efc47ca8a1778bb17a58eda9638a?view=overview
Solana -> Ethereum https://wormholescan.io/#/tx/49hbt6qpiiCvbg6aE9YbSVHSz9aur7A67N1PMbymSwG9TGvijuXTxzJNkNyhEjdQ18U32Tk7phwuMzWWV8x9AXbP
LUMOS
Fantom → Solana: https://wormholescan.io/#/tx/0xf5e732602ac3354ba168399af8f331456b1691e77272c7275c9ec74760dbd682 
Solana → Fantom: https://wormholescan.io/#/tx/3gFb3iSFtuHFpejBmKXNSyrmrbpoS2bAEeGXus33pLuTyHAirgjYr2MwUukTL954NjxjnJNWYhZUa5GU3Bsfc36D?view=overview
> Include Tower and Lumos tokens

- apps/connect/src/env/token-bridge.mainnet.ts
> Include HarryPotterObamaSonic10Inu token

- apps/connect/public/data/banners.json
- apps/connect/src/components/atoms/Bar.tsx
- apps/connect/src/components/atoms/NewsBarButton.tsx
> Banner updates

- src/components/TokenSelectors/SeiTokenPicker.tsx
- src/hooks/useGetTargetParsedTokenAccounts.ts
- src/hooks/useHandleTransfer.tsx
- src/hooks/useSeiNativeBalances.ts
Ticket: https://xlabs-xyz.atlassian.net/browse/POR-175
- Have transfer with payload in Aptos.
- List and transfer CW20 tokens in Sei.
> Sei CW20 tokens

- apps/connect/package-lock.json
- apps/connect/package.json
- apps/connect/public/data/banners.json
- apps/connect/src/env/usdc-bridge.mainnet.ts
- apps/connect/src/env/usdc-bridge.testnet.ts
- apps/connect/src/env/usdc-bridge.ts
> Aptos CCTP connect

- apps/connect/src/env/token-bridge.mainnet.ts
[POR-214](https://xlabs-xyz.atlassian.net/browse/POR-214)
[POR-214]: https://xlabs-xyz.atlassian.net/browse/POR-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CreatorBid NTT config added

- apps/connect/src/env/token-bridge.mainnet.ts
[POR-200](https://xlabs-xyz.atlassian.net/browse/POR-200)
[POR-200]: https://xlabs-xyz.atlassian.net/browse/POR-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Layer 3 NTT expansion

- apps/connect/package-lock.json
- apps/connect/package.json
- apps/connect/src/env/token-bridge.mainnet.ts
- apps/connect/src/theme/connect.ts
[POR-245](https://xlabs-xyz.atlassian.net/browse/POR-245)
[POR-245]: https://xlabs-xyz.atlassian.net/browse/POR-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Connect version 2.2.0 beta 0

- apps/connect/package-lock.json
- apps/connect/package.json
- apps/connect/src/env/usdc-bridge.mainnet.ts
- apps/connect/src/env/usdc-bridge.testnet.ts
Update connect to 2.2.0
Fix of an issue: https://github.com/XLabs/portal-bridge-ui/issues/1297
> Update Connect to 2.2.0

- src/App.tsx
> Remove rewards link
